---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: headlamp-oidc-credentials
  namespace: saas-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: SecretStore
  target:
    name: headlamp-oidc-credentials
    creationPolicy: Owner
  data:
    - secretKey: clientID
      remoteRef:
        key: headlamp-oidc-credentials
        property: clientID
    - secretKey: clientSecret
      remoteRef:
        key: headlamp-oidc-credentials
        property: clientSecret
    - secretKey: issuerURL
      remoteRef:
        key: headlamp-oidc-credentials
        property: issuerURL
    - secretKey: scopes
      remoteRef:
        key: headlamp-oidc-credentials
        property: scopes
