---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: headlamp-oidc-credentials
  namespace: saas-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: SecretStore
  target:
    name: headlamp-oidc-credentials
    creationPolicy: Owner
  data:
    - secretKey: OIDC_CLIENT_ID
      remoteRef:
        key: headlamp-oidc-credentials
        property: clientID
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: headlamp-oidc-credentials
        property: clientSecret
    - secretKey: OIDC_ISSUER_URL
      remoteRef:
        key: headlamp-oidc-credentials
        property: issuerURL
    - secretKey: OIDC_SCOPES
      remoteRef:
        key: headlamp-oidc-credentials
        property: scopes
