---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dockerio-image-pull-secret
  namespace: saas-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: SecretStore
  target:
    name: dockerio-image-pull-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {"auths":{"https://registry-1.docker.io":{"username":"{{ .username }}","password":"{{ .password }}","auth":"{{ printf "%s:%s" .username .password | b64enc }}"}}}
  data:
    - secretKey: username
      remoteRef:
        key: dockerio-registry-credentials
        property: username
    - secretKey: password
      remoteRef:
        key: dockerio-registry-credentials
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dockerio-helm-chart
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: SecretStore
  target:
    name: dockerio-helm-chart
    creationPolicy: Owner
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        name: dockerio-helm-chart
        type: helm
        url: registry-1.docker.io
        enableOCI: "true"
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: dockerio-registry-credentials
        property: username
    - secretKey: password
      remoteRef:
        key: dockerio-registry-credentials
        property: password
