---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: step-ca-root-cert-secret
  namespace: saas-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: SecretStore
  target:
    name: step-ca-root-cert-secret
    creationPolicy: Owner
  data:
    - secretKey: ca.crt
      remoteRef:
        key: step-ca-root-cert
        property: ca.crt
