server:
  config:
    persistence:
      default:
        driver: "sql"

        sql:
          driver: "postgres12"
          host: temporal-db-rw.saas-system.svc.cluster.local
          port: 5432
          database: temporal
          user: temporal
          existingSecret: temporal-db-credentials
          maxConns: 20
          maxIdleConns: 20
          maxConnLifetime: "1h"

      visibility:
        driver: "sql"

        sql:
          driver: "postgres12"
          host: temporal-db-rw.saas-system.svc.cluster.local
          port: 5432
          database: temporal_visibility
          user: temporal
          existingSecret: temporal-db-credentials
          maxConns: 20
          maxIdleConns: 20
          maxConnLifetime: "1h"

cassandra:
  enabled: false

mysql:
  enabled: false

postgresql:
  enabled: false

prometheus:
  enabled: false

grafana:
  enabled: false
  
elasticsearch:
  enabled: false

admintools:
  enabled: true
  image:
    repository: zot.saas.internal/temporalio/admin-tools
    tag: "1.29.1-tctl-1.18.4-cli-1.5.0"
    pullPolicy: IfNotPresent

web:
  enabled: true
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      # cert-manager annotation to request certificate from step-ca
      cert-manager.io/cluster-issuer: step-ca-acme
      
      # NGINX specific annotations for ArgoCD
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      
      # external-dns annotations for automatic DNS registration
      external-dns.alpha.kubernetes.io/hostname: temporal.saas.internal
      external-dns.alpha.kubernetes.io/coredns-group: "g-saas"
      external-dns.alpha.kubernetes.io/ttl: "300"
    hosts:
      - temporal.saas.internal
    tls:
      - secretName: temporal-tls
        hosts:
          - temporal.saas.internal

schema:
  createDatabase:
    enabled: false
  setup:
    enabled: true
  update:
    enabled: true
