kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: tenant-cluster
nodes:
  - role: control-plane
  - role: worker
    labels:
      NodeGroupType: default
  # - role: worker
  #   labels:
  #     NodeGroupType: database
