events {}

http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;
  charset utf-8;

  types {
    text/plain yaml yml sh bash;
  }

  server {
    listen 80;
    server_name _;

    root /srv/saas;
    index index.html index.yaml;

    location = /bootstrap {
        default_type application/x-sh;
        add_header Content-Type application/x-sh;
        add_header Cache-Control "no-store";
        try_files /tenants/bootstrap.sh =404;
    }

    error_page 403 /403.html;
    location = /403.html {
      internal;
    }
    error_page 404 /404.html;
    location = /404.html {
      internal;
    }
  }
}
