events {}

http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;

  types {
    text/plain yaml yml;
  }

  server {
    listen 80;
    server_name _;

    root /srv/saas;
    index index.html index.yaml;

    location ~* \.(yaml|yml)$ {
      default_type text/plain;
      add_header Content-Type "text/plain; charset=utf-8" always;
      add_header Content-Disposition "inline" always;
    }

    location /kubevela-addons/ {
      add_header Cache-Control "public, max-age=31536000, immutable";
      add_header Content-Type "text/plain; charset=utf-8" always;
    }

    location / {}

    location /charts/ {
      add_header Cache-Control "public, max-age=31536000, immutable";
    }
  }
}
