global:
  environment: internal
infra:
  project: default
  destination:
    server: https://kubernetes.default.svc
  source:
    repoUrl: https://github.com/taufiqibrahim/saas-data-platform-on-kubernetes.git
    targetRevision: main
keycloak:
  enabled: false
temporal:
  enabled: false
