---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenant-workspace-controller
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      application: tenant-workspace-controller
  template:
    metadata:
      labels:
        application: tenant-workspace-controller
    spec:
      serviceAccountName: tenant-workspace-controller-sa
      containers:
      - name: controller
        image: zot.saas.internal.saas/tenant-workspace-controller:0.0.6
