apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: rustfs-store
spec:
  configuration:
    destinationPath: s3://saas/database-backups/barmancloud/
    endpointURL: https://rustfs.saas.internal:9000
    endpointCA:
      name: step-ca-root-cert-secret
      key: ca.crt
    s3Credentials:
      accessKeyId:
        name: rustfs-credentials
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: rustfs-credentials
        key: ACCESS_SECRET_KEY
    wal:
      compression: gzip