apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak-db-cluster
spec:
  instances: 2
  bootstrap:
    initdb:
      database: keycloak
      owner: keycloak
      secret:
        name: keycloak-db-credentials
  storage:
    size: 4Gi

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: rustfs-barman-object-store
