apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: temporal-db
spec:
  instances: 1
  bootstrap:
    initdb:
      database: temporal
      owner: temporal
      secret:
        name: temporal-db-credentials
  storage:
    size: 4Gi

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: rustfs-barman-object-store
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: temporal-visibility
spec:
  name: temporal_visibility
  owner: temporal
  cluster:
    name: temporal-db
