apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  annotations:
    argocd.argoproj.io/manifest-generate-paths: /deployments/infra/external-secrets
    argocd.argoproj.io/sync-wave: "-10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "{{ .Values.infra.source.repoUrl }}"
    targetRevision: "{{ .Values.infra.source.targetRevision }}"
    path: deployments/saas/gitops/deployments/infra/external-secrets
  destination:
    server: {{ .Values.infra.destination.server }}
    namespace: saas-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true