{{- if .Values.headlamp.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: headlamp
  annotations:
    argocd.argoproj.io/manifest-generate-paths: /deployments/saas/gitops/deployments/core/headlamp
    argocd.argoproj.io/sync-wave: "5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    # Chart from original reference remote repo
    - repoURL: https://kubernetes-sigs.github.io/headlamp/
      chart: headlamp
      targetRevision: 0.40.0
      helm:
        valueFiles:
          - $values/deployments/saas/gitops/deployments/core/headlamp/values-{{ .Values.global.environment }}.yaml   # this points to the file in our git
    # Reference values from our git
    - repoURL: "{{ .Values.infra.source.repoURL }}"
      targetRevision: "{{ .Values.infra.source.targetRevision }}"
      ref: values
  destination:
    server: {{ .Values.infra.destination.server }}
    namespace: saas-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}
