namespaceOverride: "saas-system"
config:
  extraArgs:
  # - --oidc-skip-tls-verify
  - --oidc-use-pkce=true
  - --oidc-ca-file=/home/headlamp/.config/Headlamp/certs/stepca-root.crt
  oidc:
    secret:
      create: true
    externalSecret:
      enabled: true
      name: headlamp-oidc-credentials

# for saas.internal experiment only
# we need to allow Headlamp to trust StepCA root cert
# Headlamp containers volume mounts
volumeMounts:
  - name: stepca-root
    mountPath: /home/headlamp/.config/Headlamp/certs
    readOnly: true
#   - name: "headlamp-kubeconfig"
#     mountPath: "/home/headlamp/.config/Headlamp/kubeconfigs"
#     # subpath should match the key in secret and will be mounted as a file named "config"
#     # subPath: kubeconfig
volumes:
  - name: stepca-root
    secret:
      secretName: step-ca-root-cert-secret
      items:
        - key: ca.crt
          path: stepca-root.crt
#   - name: "headlamp-kubeconfig"
#     secret:
#       secretName: "kubeconfig-consumer-secret"
# env:
#   - name: KUBECONFIG 
#     value: "/home/headlamp/.kube/config"
ingress:
  enabled: true
  ingressClassName: "nginx"
  annotations:
    # cert-manager annotation to request certificate from step-ca
    cert-manager.io/cluster-issuer: step-ca-acme
    
    # NGINX specific annotations
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    
    # external-dns annotations for automatic DNS registration
    external-dns.alpha.kubernetes.io/hostname: headlamp.saas.internal
    external-dns.alpha.kubernetes.io/coredns-group: "g-saas"
    external-dns.alpha.kubernetes.io/ttl: "300"
  hosts:
    - host: headlamp.saas.internal
      paths:
        - path: /
          type: ImplementationSpecific
          backend:
            service:
              name: headlamp
              port:
                number: 80
  tls:
    - secretName: headlamp-tls
      hosts:
        - headlamp.saas.internal